### ISSUE TITLE
License violation

### ISSUE THREAD

**Issue by sindresorhus** [stevenselcuk/garlic#2]
You're are not following the MIT license. 

https://github.com/stevenselcuk/garlic/blob/265113eec188663d3ced1f380a8698a448fecc7b/garlic/Utils.swift is copied directly from https://github.com/sindresorhus/Plash/blob/7c150b53cc421b2615a7feb9d0ca3d45ed68d5c5/Plash/Utilities.swift

**Comment by stevenselcuk** [comment]
Removed.
